# Change these first
owner: teamcoldricalcs # Your GitHub username
repo: statuspage # Your GitHub repository name

# Add your sites here
sites:
  - name: Main Site
    url: https://coldricalcs.com
  - name: CDN (Cloudinary)
    url: https://res.cloudinary.com/dhi83lpnp/image/upload/v1612812038/latest_zsmlic.jpg
  - name: Help Centre
    url: https://help.coldricalcs.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  cname: status.coldricalcs.com
  favicon: https://raw.githubusercontent.com/teamcoldricalcs/status/master/assets/icon-transparent.png
  logoUrl: https://raw.githubusercontent.com/teamcoldricalcs/status/master/assets/wordmark-transparent.png
  name: Coldricalcs Status
  introTitle: "Keep up-to-date with the current status of Coldricalcs!"
  introMessage: This is status page is automatically updated every time we have an issue and is updated by Coldricalcs staff during every incident.
  navbar:
    - title: Home
      href: https://coldricalcs.com
    - title: Help Centre
      href: https://help.coldricalcs.com/
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
